"""
Django settings for eButik project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis le fichier .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v!%m7r26*exj!qxfazcd%s(tba68zzf_dgc2)sd2&su4xxk&(m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # Local apps
     'core',
     'panier',
     'paiement',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eButik.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'panier.context_processors.panier',
            ],
        },
    },
]

WSGI_APPLICATION = 'eButik.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Media files
# https://docs.djangoproject.com/en/4.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "eButik Admin",
    "site_header": "eButik",
    "site_brand": "eButik, Admin Area",
    "login_logo": "media/logo.png",
    "welcome_sign": "Bienvenue dans l'admin eButik",
    "copyright": "eButik Ltd",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["core", "paiement", "panier"],
    "custom_links": {},
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.category": "fas fa-tags",
        "core.product": "fas fa-box",
        "core.customer": "fas fa-user-friends",
        "core.order": "fas fa-shopping-cart",
        "core.orderitem": "fas fa-list",
        "core.profil": "fas fa-id-card",
        "core.size": "fas fa-ruler",
        "core.productsize": "fas fa-expand",
        "core.shippingoption": "fas fa-truck",
        "paiement.commande": "fas fa-receipt",
        "paiement.itemcommande": "fas fa-clipboard-list",
        "panier": "fas fa-shopping-basket",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {},
    "language_chooser": False,
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.User"},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "custom_links": {
        "core": [{
            "name": "Voir le site",
            "url": "/",
            "icon": "fas fa-external-link-alt",
            "permissions": ["core.view_product"]
        }]
    },
    "changeform_format": "horizontal_tabs",
    "dashboard": {
        "title": "Dashboard eButik",
        "cards": [
            {
                "title": "Commandes récentes",
                "model": "core.Order",
                "filter": {"status": "pending"},
                "icon": "fas fa-shopping-cart",
                "color": "blue",
            },
            {
                "title": "Produits en stock",
                "model": "core.Product",
                "filter": {"stock__gt": 0},
                "icon": "fas fa-box",
                "color": "green",
            },
            {
                "title": "Clients actifs",
                "model": "core.Customer",
                "icon": "fas fa-users",
                "color": "purple",
            },
        ],
        "modules": [
            {
                "type": "recent_actions",
                "title": "Actions récentes",
                "limit": 10,
            },
        ],
    },
}

# Configuration de Stripe - les clés sont chargées depuis les variables d'environnement (via fichier .env)
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_SUCCESS_URL = os.getenv('STRIPE_SUCCESS_URL', 'http://127.0.0.1:8000/paiement/paiement_success.html')
STRIPE_CANCEL_URL = os.getenv('STRIPE_CANCEL_URL', 'http://127.0.0.1:8000/cancel')

# Configuration des APIs Mobile Money pour le Sénégal
# Les clés API sont chargées depuis les variables d'environnement (via fichier .env)

# Configuration Wave
WAVE_API_BASE_URL = 'https://api.wave.com/v1'
WAVE_CLIENT_ID = os.getenv('WAVE_CLIENT_ID', '')
WAVE_CLIENT_SECRET = os.getenv('WAVE_CLIENT_SECRET', '')
WAVE_WEBHOOK_SECRET = os.getenv('WAVE_WEBHOOK_SECRET', '')
WAVE_SUCCESS_URL = os.getenv('WAVE_SUCCESS_URL', 'http://127.0.0.1:8000/paiement/paiement_success.html')
WAVE_CANCEL_URL = os.getenv('WAVE_CANCEL_URL', 'http://127.0.0.1:8000/paiement/paiement_cancel.html')

# Configuration Orange Money
ORANGE_MONEY_API_BASE_URL = 'https://api.orange.com'
ORANGE_MONEY_CLIENT_ID = os.getenv('ORANGE_MONEY_CLIENT_ID', '')
ORANGE_MONEY_CLIENT_SECRET = os.getenv('ORANGE_MONEY_CLIENT_SECRET', '')
ORANGE_MONEY_MERCHANT_KEY = os.getenv('ORANGE_MONEY_MERCHANT_KEY', '')
ORANGE_MONEY_WEBHOOK_SECRET = os.getenv('ORANGE_MONEY_WEBHOOK_SECRET', '')
ORANGE_MONEY_SUCCESS_URL = os.getenv('ORANGE_MONEY_SUCCESS_URL', 'http://127.0.0.1:8000/paiement/paiement_success.html')
ORANGE_MONEY_CANCEL_URL = os.getenv('ORANGE_MONEY_CANCEL_URL', 'http://127.0.0.1:8000/paiement/paiement_cancel.html')

# Configuration Lemfi
LEMFY_API_BASE_URL = 'https://api.lemfi.com/v1'
LEMFY_API_KEY = os.getenv('LEMFY_API_KEY', '')
LEMFY_SECRET_KEY = os.getenv('LEMFY_SECRET_KEY', '')
LEMFY_WEBHOOK_SECRET = os.getenv('LEMFY_WEBHOOK_SECRET', '')
LEMFY_SUCCESS_URL = os.getenv('LEMFY_SUCCESS_URL', 'http://127.0.0.1:8000/paiement/paiement_success.html')
LEMFY_CANCEL_URL = os.getenv('LEMFY_CANCEL_URL', 'http://127.0.0.1:8000/paiement/paiement_cancel.html')

# Configuration générale des paiements mobile money
MOBILE_MONEY_CONFIG = {
    'wave': {
        'api_base_url': WAVE_API_BASE_URL,
        'client_id': WAVE_CLIENT_ID,
        'client_secret': WAVE_CLIENT_SECRET,
        'webhook_secret': WAVE_WEBHOOK_SECRET,
        'success_url': WAVE_SUCCESS_URL,
        'cancel_url': WAVE_CANCEL_URL,
        'timeout': 30,  # secondes
    },
    'orange': {
        'api_base_url': ORANGE_MONEY_API_BASE_URL,
        'client_id': ORANGE_MONEY_CLIENT_ID,
        'client_secret': ORANGE_MONEY_CLIENT_SECRET,
        'merchant_key': ORANGE_MONEY_MERCHANT_KEY,
        'webhook_secret': ORANGE_MONEY_WEBHOOK_SECRET,
        'success_url': ORANGE_MONEY_SUCCESS_URL,
        'cancel_url': ORANGE_MONEY_CANCEL_URL,
        'timeout': 30,
    },
    'lemfi': {
        'api_base_url': LEMFY_API_BASE_URL,
        'api_key': LEMFY_API_KEY,
        'secret_key': LEMFY_SECRET_KEY,
        'webhook_secret': LEMFY_WEBHOOK_SECRET,
        'success_url': LEMFY_SUCCESS_URL,
        'cancel_url': LEMFY_CANCEL_URL,
        'timeout': 30,
    }
}

