# Generated by Django 4.2.27 on 2025-12-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_is_on_sale_product_original_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='telephone',
        ),
    ]
