# Generated by Django 4.2.27 on 2026-01-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ancien_panier',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
