# Generated by Django 4.2.27 on 2026-01-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profil_ancien_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ancien_panier_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ancien_panier',
            field=models.TextField(blank=True),
        ),
    ]
