# Generated by Django 4.2.27 on 2026-01-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profil_ancien_panier_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='ancien_panier_updated',
        ),
    ]
