# Generated by Django 4.2.27 on 2026-01-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profil_ancien_panier_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ville',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
