# Generated by Django 4.2.27 on 2026-03-08 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_payment_method_order_payment_reference_and_more'),
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='core_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order', verbose_name='commande core'),
        ),
    ]
